name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  #release:
    #types:
      #- created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions :
      contents: read
      packages : write
      id-token : write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true # improving perfs by enabling caching for the flutter SDK
      - run: flutter pub get
      - run: flutter build web --dart-define=APP_VERSION=${{github.ref_name}} --dart-define=PLANT_ID_API_KEY=${{secrets.PLANT_ID_API_KEY}}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0 #todo changer pr action offi gh
        with:
          branch: gh-pages
          folder: build/web
          token: ${{ secrets.ACCESS_TOKEN }}
    